NGLPteam/meru-api

app/graphql/types/contributor_type.rb, app/graphql/types/query_type.rb, app/models/community.rb, app/operations/mutations/contracts/community_input.rb, app/operations/mutations/operations/create_community.rb, app/operations/mutations/operations/update_community.rb, spec/requests/graphql/mutations/create_community_spec.rb, spec/requests/graphql/mutations/update_community_spec.rb, spec/requests/graphql/query/user_spec.rb
Resolves WDP-184
Resolves WDP-185
=> [F] Add user type, validate community title presence

app/graphql/mutations/create_collection.rb, app/graphql/mutations/create_item.rb, app/graphql/mutations/update_collection.rb, app/graphql/mutations/update_item.rb, app/graphql/types/query_type.rb, app/graphql/types/user_type.rb, app/models/collection.rb, app/models/concerns/auto_identifier.rb, app/models/concerns/contribution.rb, app/models/concerns/has_ephemeral_system_slug.rb, app/models/concerns/has_schema_definition.rb, app/models/item.rb, spec/factories/contributions.rb, spec/requests/graphql/mutations/create_collection_spec.rb, spec/requests/graphql/mutations/create_item_spec.rb, spec/requests/graphql/query/collection_contribution_spec.rb, spec/requests/graphql/query/item_contribution_spec.rb, spec/requests/graphql/query/user_spec.rb
Resolves WDP-200
Resolves WDP-198
Resolves WDP-188
=> [F] Various API Changes

app/graphql/types/query_type.rb, app/models/asset.rb, spec/requests/graphql/query/asset_spec.rb
=> [F] Add `Query.asset`

.rubocop.yml, app/graphql/types/base_enum.rb, app/services/app_types.rb, app/services/schemas/properties/scalar/base.rb, app/services/schemas/properties/scalar/boolean.rb, app/services/schemas/properties/scalar/date.rb, app/services/schemas/properties/scalar/email.rb, app/services/schemas/properties/scalar/float.rb, app/services/schemas/properties/scalar/full_text.rb, app/services/schemas/properties/scalar/multiselect.rb, app/services/schemas/properties/scalar/reference.rb, app/services/schemas/properties/scalar/select.rb, app/services/schemas/properties/scalar/tags.rb, app/services/schemas/properties/scalar/timestamp.rb, app/services/schemas/properties/scalar/unknown.rb, app/services/schemas/properties/scalar/url.rb, app/services/schemas/properties/scalar/variable_date.rb, lib/variable_precision_date.rb, spec/operations/full_text/normalizer_spec.rb, spec/operations/variable_precision/parse_date_spec.rb, spec/requests/graphql/mutations/update_global_configuration_spec.rb, spec/requests/graphql/schemas/journal_article_spec.rb, spec/support/contexts/applies_schema_properties.rb, spec/support/graphql/apply_schema_properties.graphql, spec/support/helpers/graphql_helpers.rb
* Ensure that enums for variable precision dates and full text
schematic properties are being properly converted when provided
through the API
* Add proper test coverage for setting properties on the
`nglp:journal_article` schema
* Add test helper for building out GraphQL responses from mutations
* Add default GraphQL query for applySchemaProperties mutation, to be
used for testing other schemas as needed
=> [B] Resolve and Validate Complex Schema Inputs

app/graphql/mutations/update_asset.rb, app/graphql/mutations/update_asset_attachment.rb, app/graphql/types/mutation_type.rb
=> [C] Expose `updateAsset`, `updateAssetAttachment`

app/graphql/types/asset_type.rb, app/operations/mutations/operations/update_asset.rb
* Expose `Asset.altText`
* Ensure `UpdateAssetInput.attachment` is actually optional
Resolves WDP-612
=> [C] Improve Asset Interface & updateAsset Mutation

app/graphql/mutations/update_global_configuration.rb, app/graphql/types/global_configuration_type.rb, app/graphql/types/settings/institution_settings_input_type.rb, app/graphql/types/settings/institution_settings_type.rb, app/graphql/types/settings/site_settings_input_type.rb, app/graphql/types/settings/site_settings_type.rb, app/models/concerns/child_entity.rb, app/models/harvest_record.rb, app/operations/harvesting/actions/parse_record_metadata.rb, app/operations/harvesting/metadata/formats/jats.rb, app/operations/harvesting/metadata/formats/mets.rb, app/operations/harvesting/metadata/jats/extract_entities.rb, app/operations/harvesting/metadata/jats/parse.rb, app/operations/harvesting/metadata/jats/parse_sortable_number.rb, app/operations/harvesting/metadata/mets/parse.rb, app/operations/mutations/contracts/update_global_configuration.rb, app/operations/mutations/operations/update_global_configuration.rb, app/services/harvesting/metadata/base_format.rb, app/services/harvesting/metadata/jats/parsed.rb, app/services/harvesting/metadata/value_extraction/dsl/builder.rb, app/services/harvesting/metadata/value_extraction/error.rb, app/services/harvesting/metadata/value_extraction/struct.rb, app/services/settings/site.rb, spec/requests/graphql/mutations/update_global_configuration_spec.rb
=> [C] Update issue metadata; add installation name

app/graphql/types/image_attachment_type.rb, app/graphql/types/image_identification_type.rb, app/graphql/types/image_purpose_type.rb, app/graphql/types/image_size_type.rb, app/graphql/types/image_type.rb, app/services/graphql/image_attachment_support.rb, app/services/image_attachments/derivative_wrapper.rb, app/services/image_attachments/image_wrapper.rb, app/services/image_attachments/original_wrapper.rb, app/services/image_attachments/size_wrapper.rb, app/services/image_attachments/types.rb, app/services/resolvers/search_result_resolver.rb, spec/requests/graphql/mutations/create_community_spec.rb
=> [F] Search by schema; expose original image filenames

app/graphql/types/image_size_type.rb, app/jobs/entities/reprocess_all_derivatives_job.rb, app/jobs/entities/reprocess_derivative_job.rb, app/jobs/entities/reprocess_derivatives_job.rb, app/operations/harvesting/metadata/jats/extract_entities.rb, app/services/harvesting/metadata/jats/parsed.rb, app/services/image_attachments/constants.rb, app/services/image_attachments/size.rb, lib/schemas/definitions/nglp/dissertation/1.0.0.json, lib/schemas/definitions/nglp/journal/1.0.0.json, lib/schemas/definitions/nglp/journal_article/1.0.0.json, lib/schemas/definitions/nglp/journal_issue/1.0.0.json, lib/schemas/definitions/nglp/journal_volume/1.0.0.json, lib/tasks/entities.rake, spec/jobs/entities/reprocess_all_derivatives_job_spec.rb, spec/jobs/entities/reprocess_derivative_job_spec.rb, spec/jobs/entities/reprocess_derivatives_job_spec.rb
Resolves WDP-702
Resolves WDP-520
=> [F] Harvesting & Minor Issue Updates

app/graphql/types/slug_type.rb, app/graphql/types/user_type.rb, app/services/anonymous_interface.rb, spec/requests/graphql/query/viewer_spec.rb
=> [B] Correctly resolve `Query.viewer` anonymously

app/graphql/types/entity_descendant_type.rb, app/models/concerns/hierarchical_entity.rb
=> [C] Don’t preload entity descendants

app/jobs/entities/audit_mismatched_schemas_job.rb, app/models/audits.rb, app/models/audits/mismatched_entity_schema.rb, app/operations/schemas/instances/alter_version.rb, config/initializers/900_zhong.rb, db/migrate/20220607175341_create_audits_mismatched_entity_schemas.rb, db/structure.sql, db/views/audits_mismatched_entity_schemas_v01.sql, spec/jobs/entities/audit_mismatched_schemas_job_spec.rb, spec/models/audits/mismatched_entity_schema_spec.rb, spec/requests/graphql/mutations/alter_schema_version_spec.rb
=> [B] Ensure synchronized entity has correct schema

app/jobs/harvesting/extract_record_job.rb, app/jobs/harvesting/extract_records_job.rb, app/jobs/harvesting/reextract_record_job.rb, app/jobs/harvesting/upsert_entity_assets_job.rb, app/jobs/pilot_harvesting/seed_job.rb, config/sidekiq.yml
=> [C] Expand harvesting queues

app/models/harvest_record.rb, app/operations/collections/upsert.rb, app/operations/harvesting/metadata/oaidc/extract_entities.rb, app/operations/harvesting/middleware/builders/from_harvest_mapping.rb, app/operations/harvesting/middleware/builders/from_harvest_source.rb, app/operations/harvesting/utility/parse_journal_source.rb, app/services/harvesting/metadata/oaidc/parsed.rb, app/services/harvesting/options/mapping.rb, app/services/harvesting/utility/parsed_journal_source.rb, app/services/pilot_harvesting/harvestable.rb, lib/frozen_record/pilot_communities.yml, spec/operations/harvesting/utility/parse_journal_source_spec.rb
* Allow volumes and issues to be auto-created as 1/1 respectively when treating as journal articles
* Allow OAIDC to produce a paper in a series instead of a journal
=> [F] Improve harvesting for certain OAIDC use cases

app/graphql/mutations/update_global_configuration.rb, app/graphql/types/global_configuration_type.rb, app/graphql/types/settings/entities_settings_input_type.rb, app/graphql/types/settings/entities_settings_type.rb, app/models/global_configuration.rb, app/operations/mutations/contracts/update_global_configuration.rb, app/operations/mutations/operations/update_global_configuration.rb, app/services/settings/entities.rb, db/migrate/20240807162748_add_entities_to_global_configurations.rb, db/structure.sql, lib/frozen_record/static_cached_columns.yml, spec/requests/graphql/mutations/update_global_configuration_spec.rb
=> [F] Add setting for suppressing external links

app/models/asset.rb
=> [B] Ensure proper filename is returned on download

app/graphql/types/page_info_type.rb, app/services/resolvers/abstract_resolver.rb, app/services/resolvers/filters_by_schema_name.rb, app/services/resolvers/search_result_resolver.rb, lib/support/lib/graphql_api/enhancements/abstract_object.rb
* Ensure that count caches are tracked correctly based on the args that are passed into the resolver.
* Update documentation
=> [F] Allow searching to filter just by schema

app/graphql/types/template_entity_list_type.rb, app/services/templates/entity_list.rb, spec/support/shared_examples/a_graphql_entity_with_layouts.rb
* Add test coverage
* Address discovered edge case with missing layouts
=> [B] Correct template entity list associations

.rubocop.yml, app/models/concerns/has_schema_definition.rb, app/models/ordering_entry_candidate.rb, app/services/templates/entity_lists/named_resolver.rb, lib/schemas/definitions/nglp/journal_article/1.0.0/config.json, spec/factories/collections.rb, spec/factories/communities.rb, spec/factories/items.rb, spec/models/entity_orderable_property_spec.rb, spec/operations/templates/entity_lists/resolve_named_spec.rb, spec/requests/graphql/query/communities_spec.rb, spec/requests/graphql/query/schema_instance_spec.rb, spec/requests/graphql/query_spec.rb, spec/requests/graphql/schemas/journal_article_spec.rb, spec/support/contexts/journal_hierarchy.rb, spec/support/helpers/operation_helpers.rb
* Improve testability of journal hierarchies significantly
* Relax required properties on journal article in preparation for schema refactoring
=> [B] Fix issue with named entity list in templates

app/operations/harvesting/attempts/extract_records.rb, app/operations/harvesting/utility/parse_journal_source.rb, lib/frozen_record/pilot_communities.yml
* Address issue with missing page numbers when parsing journal source
* Address issue with missing logger in record extraction operation
=> [C] Add additional pilots for BTAA

lib/schemas/definitions/nglp/journal_issue/1.0.0/config.json
=> [E] Add PDF version to journal issues

app/graphql/mutations/upsert_contribution.rb, app/graphql/types/contribution_base_type.rb, app/graphql/types/layout_instance_type.rb, app/graphql/types/template_instance_type.rb, app/graphql/types/template_slot_instance_type.rb, app/models/concerns/layout_instance.rb, app/operations/attributions/collections/upsert.rb, app/operations/attributions/items/upsert.rb, app/operations/mutations/contracts/upsert_contribution.rb, app/operations/mutations/operations/upsert_contribution.rb, app/services/contributions/attacher.rb, app/services/shared/type_registry.rb, db/migrate/20250205231244_alter_contribution_positions.rb, db/structure.sql, lib/controlled_vocabularies/meru.host/marc_codes/1.0.0.json, lib/frozen_record/static_cached_columns.yml, spec/requests/graphql/mutations/upsert_contribution_spec.rb, spec/support/shared_examples/a_graphql_entity_with_layouts.rb
=> [E] Contribution Role Improvements

app/graphql/types/describes_schema_type.rb, app/graphql/types/schema_version_type.rb, app/models/concerns/template_instance.rb, app/models/hierarchical_schema_rank.rb, app/models/hierarchical_schema_version_rank.rb, app/models/template.rb, app/models/templates/detail_instance.rb, app/operations/schemas/static/load_definitions.rb, app/operations/schemas/versions/maintain_associations.rb, app/services/templates/config/template_slots/hero_slots.rb, app/services/templates/instances/has_announcements.rb, app/services/templates/slot_mappings/hero_definition_slots.rb, app/services/templates/slot_mappings/hero_instance_slots.rb, db/migrate/20250217215855_add_enforced_kinds_to_schema_versions.rb, db/structure.sql, lib/frozen_record/static_cached_columns.yml, lib/frozen_record/template_slots.yml, lib/frozen_record/templates.yml, lib/generators/template/templates/instance.rb.tt
* Always show detail templates if showAnnouncements and announcements exist
* Expose enforced parent/child kinds on schemas, fix bug with operation that generates these associations
* Add new hero slots for subtitles
=> [E] More template / schema improvements

app/graphql/types/abstract_model.rb, app/graphql/types/ordering_entry_type.rb, app/models/ordering_entry.rb, app/models/ordering_entry_ancestor_link.rb, app/policies/ordering_entry_policy.rb, spec/models/ordering_entry_ancestor_link_spec.rb
=> [B] Fix ordering entry ancestor associations

app/graphql/types/entity_type.rb, app/jobs/entities/purge_job.rb, app/models/concerns/hierarchical_entity.rb, app/models/concerns/inline_rendering.rb, config/database.yml, config/initializers/900_good_job.rb, spec/support/shared_examples/a_graphql_entity_with_layouts.rb
* Fix typo in concurrency lock for entity purge job
* Allow entity templates to render inline
* Increase DB pool size
* Adjust GJ concurrency
=> [E] Miscellaneous fixes

lib/schemas/definitions/nglp/collected_article/1.0.0/layouts/hero.xml, lib/schemas/definitions/nglp/collected_article/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/collected_volume/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/dissertation/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/journal_article/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/journal_issue/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/journal_volume/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/paper/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/series/1.0.0/config.json, lib/schemas/definitions/nglp/series/1.0.0/layouts/list_item.xml, lib/schemas/definitions/nglp/series/1.0.0/layouts/main.xml, lib/schemas/definitions/nglp/unit/1.0.0/layouts/list_item.xml
Resolves:
- MERU-1029
- MERU-1036
=> [B][E] Layout improvements

app/models/controlled_vocabulary.rb, app/operations/controlled_vocabularies/lookup.rb, app/operations/controlled_vocabularies/static/seed_all.rb, app/services/controlled_vocabularies/finder.rb, app/services/controlled_vocabularies/types.rb, app/services/harvesting/extraction/environment_builder.rb, app/services/harvesting/extraction/file_system.rb, app/services/harvesting/extraction/mapping.rb, app/services/harvesting/extraction/mappings/props/controlled_vocabulary.rb, app/services/harvesting/extraction/mappings/schema_properties.rb, app/services/harvesting/extraction/mappings/template.rb, app/services/harvesting/extraction/mappings/templates.rb, app/services/harvesting/extraction/render_context.rb, lib/controlled_vocabularies/meru.host/common_licenses/1.0.0.json, lib/harvesting/examples/default_pressbooks/template.xml, lib/schemas/definitions/nglp/book/1.0.0/config.json, lib/schemas/definitions/nglp/book/1.0.0/layouts/hero.xml, lib/schemas/definitions/nglp/book/1.0.0/layouts/metadata.xml, lib/schemas/definitions/nglp/book_section/1.0.0/config.json
* Add ability to have reusable liquid templates in mapping template
* Add support for controlled vocabulary properties
* Add common licenses CV
* Add license CV props to book and book sections
* Add index / position props when enumerating in harvesting
* Update default pressbooks harvesting mapping template
=> [F] Implement harvesting improvements for PB
